name: Terraform Plan

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'terraform/**'

permissions:
  contents: read
  pull-requests: write

jobs:
  plan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name: Terraform Init
        working-directory: terraform/envs/staging
        run: |
          set -euo pipefail
          terraform init -input=false

      - name: Terraform Plan
        working-directory: terraform/envs/staging
        run: |
          set -euo pipefail
          terraform plan -input=false -no-color
